#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Semantic-map file-queue matching service.

This script is intended to run outside ROS, for example in a conda Python3.10/3.11
CUDA environment. It reads queue requests produced by eloftr_queue_exporter.py,
constructs a local geometric-semantic BEV map and a satellite semantic map, then
searches dx/dy/yaw around the current GPS/EKF pose using a semantic compatibility
score.

It writes output/result_<id>.json plus visualization images:
  semantic_local_<id>.png
  semantic_sat_<id>.png
  heatmap_<id>.png
  overlay_<id>.png

The ROS-side eloftr_queue_result_publisher.py can publish the result JSON as
/map_match_pose_external and publish heatmap/overlay images.

Semantic labels used internally:
  0 unknown/background
  1 open/road/ground
  2 building/solid structure
  3 vegetation
  4 obstacle/vertical edge
"""
import argparse
import glob
import json
import math
import os
import shutil
import time
from pathlib import Path

import cv2
import numpy as np


LABEL_UNKNOWN = 0
LABEL_OPEN = 1
LABEL_BUILDING = 2
LABEL_VEGETATION = 3
LABEL_OBSTACLE = 4

# BGR colors for visualization
SEM_COLORS = {
    LABEL_UNKNOWN: (40, 40, 40),
    LABEL_OPEN: (210, 210, 210),
    LABEL_BUILDING: (80, 80, 220),
    LABEL_VEGETATION: (60, 170, 60),
    LABEL_OBSTACLE: (40, 120, 240),
}


class SemanticFileService:
    def __init__(self, args):
        self.args = args
        self.queue_dir = Path(args.queue_dir)
        self.input_dir = self.queue_dir / 'input'
        self.output_dir = self.queue_dir / 'output'
        self.done_dir = self.queue_dir / 'done'
        for d in [self.input_dir, self.output_dir, self.done_dir]:
            d.mkdir(parents=True, exist_ok=True)
        print('[INFO] semantic service ready. queue=%s mode=%s' % (self.queue_dir, 'semantic'))

    @staticmethod
    def read_json(path):
        with open(path, 'r') as f:
            return json.load(f)

    @staticmethod
    def write_json_atomic(path, obj):
        tmp = str(path) + '.tmp'
        with open(tmp, 'w') as f:
            json.dump(obj, f, indent=2)
        os.replace(tmp, str(path))

    @staticmethod
    def meta_dict(req):
        meta = req.get('meta', [])
        names = req.get('meta_layout', [])
        return {names[i]: float(meta[i]) for i in range(min(len(meta), len(names)))}

    @staticmethod
    def ensure_bgr(img):
        if img is None:
            return None
        if len(img.shape) == 2:
            return cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        if img.shape[2] == 4:
            return cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
        return img

    @staticmethod
    def colorize_labels(label):
        h, w = label.shape
        out = np.zeros((h, w, 3), dtype=np.uint8)
        for k, c in SEM_COLORS.items():
            out[label == k] = c
        return out

    @staticmethod
    def largest_dim_resize(img, max_dim, interpolation=cv2.INTER_AREA):
        if max_dim <= 0:
            return img, 1.0
        h, w = img.shape[:2]
        m = max(h, w)
        if m <= max_dim:
            return img, 1.0
        scale = float(max_dim) / float(m)
        nw = max(16, int(round(w * scale)))
        nh = max(16, int(round(h * scale)))
        return cv2.resize(img, (nw, nh), interpolation=interpolation), scale

    def infer_local_semantic(self, bgr_or_gray, structure_gray=None):
        """Heuristic local geometric-semantic BEV segmentation.

        It is designed for /local_bev/image generated by v9+ C++ node:
          - light gray-blue: observed ground/open area
          - dark/red pixels: obstacles, vertical structures, high objects
        If a real semantic BEV label image is available, replace this function or
        publish that label image to the exporter topic.
        """
        img = self.ensure_bgr(bgr_or_gray)
        b, g, r = cv2.split(img)
        hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        h, s, v = cv2.split(hsv)
        mean = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        label = np.zeros(mean.shape, dtype=np.uint8)

        # Observed/open ground from the BEV visualization, low saturation light pixels.
        open_mask = (mean > self.args.local_open_min_v) & (mean < 248) & (s < self.args.local_open_max_sat)

        # Obstacle/structure pixels are dark or reddish in local BEV visualization.
        red_like = (r.astype(np.int16) > g.astype(np.int16) + self.args.local_red_margin) & (r.astype(np.int16) > b.astype(np.int16) + self.args.local_red_margin)
        dark_structure = (mean < self.args.local_obstacle_max_v) & (s > self.args.local_obstacle_min_sat)
        strong_structure = red_like | dark_structure

        # If mono structure image exists, use its strong responses as additional obstacle/edge evidence.
        if structure_gray is not None:
            sg = structure_gray if len(structure_gray.shape) == 2 else cv2.cvtColor(structure_gray, cv2.COLOR_BGR2GRAY)
            sg = cv2.resize(sg, (mean.shape[1], mean.shape[0]), interpolation=cv2.INTER_AREA)
            strong_structure |= (sg > self.args.local_structure_gray_thresh)
            open_mask |= ((sg > self.args.local_ground_gray_thresh) & ~strong_structure)

        # Greenish local pixels, if a semantic input is provided later.
        vegetation_mask = (g.astype(np.int16) > r.astype(np.int16) + 20) & (g.astype(np.int16) > b.astype(np.int16) + 15) & (s > 40)

        label[open_mask] = LABEL_OPEN
        label[strong_structure] = LABEL_OBSTACLE
        label[vegetation_mask] = LABEL_VEGETATION

        # Clean small speckles while preserving sparse boundaries.
        kernel = np.ones((3, 3), np.uint8)
        for lab in [LABEL_OPEN, LABEL_OBSTACLE, LABEL_VEGETATION]:
            m = (label == lab).astype(np.uint8) * 255
            if lab == LABEL_OPEN:
                m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, kernel, iterations=1)
            else:
                m = cv2.dilate(m, kernel, iterations=1)
            label[m > 0] = lab
        return label

    def infer_satellite_semantic(self, bgr, structure_gray=None):
        """Heuristic satellite semantic segmentation.

        This is a placeholder for a real satellite segmentation model. It is good
        enough for debugging the semantic matching pipeline and should be replaced
        by SegFormer/DeepLab/SAM-based segmentation for final experiments.
        """
        img = self.ensure_bgr(bgr)
        hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        h, s, v = cv2.split(hsv)
        b, g, r = cv2.split(img)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        label = np.zeros(gray.shape, dtype=np.uint8)

        # Vegetation: green dominant or HSV green/yellow-green with enough saturation.
        green_dom = (g.astype(np.int16) > r.astype(np.int16) + self.args.sat_green_margin) & (g.astype(np.int16) > b.astype(np.int16) + self.args.sat_green_margin)
        veg = (((h >= 25) & (h <= 95) & (s > self.args.sat_veg_min_sat) & (v > 35)) | green_dom)

        # Road/open: low saturation gray-ish or tan surfaces, usually not very green.
        low_sat = (s < self.args.sat_road_max_sat) & (v > self.args.sat_road_min_v) & (v < self.args.sat_road_max_v)
        # Buildings: bright, low-to-medium saturation roof regions; edge-enhanced later.
        bright_roof = (v > self.args.sat_building_min_v) & (s < self.args.sat_building_max_sat) & (~veg)
        mid_roof = (gray > self.args.sat_building_gray_min) & (~veg) & (s < self.args.sat_building_max_sat + 25)

        label[low_sat] = LABEL_OPEN
        label[bright_roof | mid_roof] = LABEL_BUILDING
        label[veg] = LABEL_VEGETATION

        # Structure image edges help convert boundaries to building/obstacle compatibility.
        if structure_gray is not None:
            sg = structure_gray if len(structure_gray.shape) == 2 else cv2.cvtColor(structure_gray, cv2.COLOR_BGR2GRAY)
            sg = cv2.resize(sg, (gray.shape[1], gray.shape[0]), interpolation=cv2.INTER_AREA)
            edges = sg > self.args.sat_structure_gray_thresh
            # Edge pixels next to building or vegetation are semantically meaningful boundaries.
            dil_building = cv2.dilate((label == LABEL_BUILDING).astype(np.uint8), np.ones((5,5),np.uint8), iterations=1) > 0
            dil_veg = cv2.dilate((label == LABEL_VEGETATION).astype(np.uint8), np.ones((5,5),np.uint8), iterations=1) > 0
            label[edges & dil_building] = LABEL_BUILDING
            label[edges & dil_veg & (label == LABEL_UNKNOWN)] = LABEL_VEGETATION

        kernel = np.ones((3,3), np.uint8)
        for lab in [LABEL_OPEN, LABEL_BUILDING, LABEL_VEGETATION]:
            m = (label == lab).astype(np.uint8) * 255
            m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, kernel, iterations=1)
            label[m > 0] = lab
        return label

    @staticmethod
    def semantic_boundary(label):
        known = label > 0
        b = np.zeros(label.shape, dtype=np.uint8)
        b[:, 1:] |= ((label[:, 1:] != label[:, :-1]) & known[:, 1:] & known[:, :-1]).astype(np.uint8)
        b[1:, :] |= ((label[1:, :] != label[:-1, :]) & known[1:, :] & known[:-1, :]).astype(np.uint8)
        # Include building/vegetation/object region contours.
        for lab in [LABEL_BUILDING, LABEL_VEGETATION, LABEL_OBSTACLE]:
            m = (label == lab).astype(np.uint8) * 255
            if m.sum() > 0:
                edges = cv2.Canny(m, 50, 150)
                b |= (edges > 0).astype(np.uint8)
        return b.astype(np.uint8)

    @staticmethod
    def compatibility(local_labels, sat_labels):
        # Vectorized semantic compatibility in [0,1].
        score = np.zeros(local_labels.shape, dtype=np.float32)
        l = local_labels
        s = sat_labels
        # open/road local should match open/road satellite, weakly with building edges.
        score[(l == LABEL_OPEN) & (s == LABEL_OPEN)] = 1.00
        score[(l == LABEL_OPEN) & (s == LABEL_BUILDING)] = 0.20
        score[(l == LABEL_OPEN) & (s == LABEL_VEGETATION)] = 0.20
        # local obstacle/structure can correspond to building walls/roofs or vegetation boundaries.
        score[(l == LABEL_OBSTACLE) & (s == LABEL_BUILDING)] = 1.00
        score[(l == LABEL_OBSTACLE) & (s == LABEL_VEGETATION)] = 0.65
        score[(l == LABEL_OBSTACLE) & (s == LABEL_OPEN)] = 0.10
        # local building, if provided by real semantic map.
        score[(l == LABEL_BUILDING) & (s == LABEL_BUILDING)] = 1.00
        score[(l == LABEL_BUILDING) & (s == LABEL_OPEN)] = 0.10
        score[(l == LABEL_BUILDING) & (s == LABEL_VEGETATION)] = 0.20
        # vegetation.
        score[(l == LABEL_VEGETATION) & (s == LABEL_VEGETATION)] = 1.00
        score[(l == LABEL_VEGETATION) & (s == LABEL_BUILDING)] = 0.25
        score[(l == LABEL_VEGETATION) & (s == LABEL_OPEN)] = 0.15
        return score

    def local_points(self, local_label, meta):
        h, w = local_label.shape
        valid = local_label > 0
        n_valid = int(valid.sum())
        fg_ratio = n_valid / float(max(1, h * w))
        if n_valid < self.args.min_local_valid_pixels or fg_ratio < self.args.min_local_foreground_ratio:
            return None, {'n_valid': n_valid, 'foreground_ratio': fg_ratio}

        # Use boundary points plus a limited number of semantic interior points.
        boundary = self.semantic_boundary(local_label) > 0
        boundary &= valid
        interior = valid & (~boundary)
        coords = []
        labels = []
        weights = []

        by, bx = np.where(boundary)
        iy, ix = np.where(interior)
        rng = np.random.default_rng(12345)
        if len(bx) > self.args.max_boundary_points:
            idx = rng.choice(len(bx), self.args.max_boundary_points, replace=False)
            bx, by = bx[idx], by[idx]
        if len(ix) > self.args.max_interior_points:
            idx = rng.choice(len(ix), self.args.max_interior_points, replace=False)
            ix, iy = ix[idx], iy[idx]

        if len(bx) > 0:
            coords.append(np.stack([bx, by], axis=1))
            labels.append(local_label[by, bx])
            weights.append(np.full(len(bx), self.args.boundary_weight, dtype=np.float32))
        if len(ix) > 0:
            coords.append(np.stack([ix, iy], axis=1))
            labels.append(local_label[iy, ix])
            weights.append(np.ones(len(ix), dtype=np.float32))
        if not coords:
            return None, {'n_valid': n_valid, 'foreground_ratio': fg_ratio}
        pix = np.concatenate(coords, axis=0).astype(np.float32)
        labs = np.concatenate(labels, axis=0).astype(np.uint8)
        wgt = np.concatenate(weights, axis=0).astype(np.float32)

        # Pixel -> local ENU meters. Use meta BEV physical extents rather than image size alone.
        bev_min_e = meta['bev_min_e']; bev_max_e = meta['bev_max_e']
        bev_min_n = meta['bev_min_n']; bev_max_n = meta['bev_max_n']
        orig_cols = meta.get('bev_cols', w); orig_rows = meta.get('bev_rows', h)
        # If image was resized by exporter/service, use current shape but same physical extent.
        u = pix[:, 0]
        v = pix[:, 1]
        local_e = bev_min_e + (u + 0.5) / float(w) * (bev_max_e - bev_min_e)
        local_n = bev_max_n - (v + 0.5) / float(h) * (bev_max_n - bev_min_n)
        return (local_e.astype(np.float32), local_n.astype(np.float32), labs, wgt), {
            'n_valid': n_valid,
            'foreground_ratio': fg_ratio,
            'n_sample': int(len(labs)),
            'n_boundary': int(len(bx)),
            'n_interior': int(len(ix)),
            'orig_cols': orig_cols,
            'orig_rows': orig_rows,
        }

    def eval_candidate(self, points, sat_label, sat_dist, meta, pose_e, pose_n, yaw_deg):
        local_e, local_n, labs, wgt = points
        yaw = math.radians(yaw_deg)
        c = math.cos(yaw); s = math.sin(yaw)
        re = c * local_e - s * local_n
        rn = s * local_e + c * local_n
        ge = pose_e + re
        gn = pose_n + rn
        h, w = sat_label.shape
        abs_min_e = meta['abs_min_e']; abs_max_e = meta['abs_max_e']
        abs_min_n = meta['abs_min_n']; abs_max_n = meta['abs_max_n']
        u = ((ge - abs_min_e) / max(1e-6, (abs_max_e - abs_min_e)) * w).astype(np.int32)
        v = ((abs_max_n - gn) / max(1e-6, (abs_max_n - abs_min_n)) * h).astype(np.int32)
        inside = (u >= 0) & (u < w) & (v >= 0) & (v < h)
        if inside.sum() < self.args.min_projected_points:
            return None
        ui = u[inside]; vi = v[inside]
        li = labs[inside]
        wi = wgt[inside]
        sat_l = sat_label[vi, ui]
        comp = self.compatibility(li, sat_l)
        sem_score = float(np.average(comp, weights=wi)) if comp.size else 0.0
        coverage = float((comp >= self.args.compat_match_thresh).sum()) / float(max(1, comp.size))
        mean_dt = float(np.average(sat_dist[vi, ui], weights=wi)) if comp.size else 999.0
        boundary_score = math.exp(-mean_dt / max(1e-6, self.args.boundary_sigma_px))
        total = (self.args.semantic_weight * sem_score +
                 self.args.boundary_score_weight * boundary_score +
                 self.args.coverage_weight * coverage)
        return {
            'score': float(total),
            'sem_score': float(sem_score),
            'coverage': float(coverage),
            'mean_dt': float(mean_dt),
            'boundary_score': float(boundary_score),
            'inside_ratio': float(inside.sum()) / float(max(1, len(labs))),
            'inside_count': int(inside.sum()),
        }

    def search(self, points, sat_label, sat_dist, meta):
        state_e = meta['state_e']; state_n = meta['state_n']
        dx_values = np.arange(-self.args.search_radius_m, self.args.search_radius_m + 1e-6, self.args.search_step_m)
        dy_values = np.arange(-self.args.search_radius_m, self.args.search_radius_m + 1e-6, self.args.search_step_m)
        yaw_values = [float(x) for x in self.args.yaw_degs.split(',')] if self.args.yaw_degs else [0.0]
        h, w = sat_label.shape
        heat = np.zeros((h, w), dtype=np.float32)
        candidates = []
        best = None
        for yaw in yaw_values:
            for dx in dx_values:
                for dy in dy_values:
                    pe = state_e + float(dx)
                    pn = state_n + float(dy)
                    ev = self.eval_candidate(points, sat_label, sat_dist, meta, pe, pn, yaw)
                    if ev is None:
                        continue
                    ev.update({'pose_e': pe, 'pose_n': pn, 'dx': float(dx), 'dy': float(dy), 'yaw_deg': yaw})
                    candidates.append(ev)
                    u = int(round((pe - meta['abs_min_e']) / max(1e-6, (meta['abs_max_e'] - meta['abs_min_e'])) * w))
                    v = int(round((meta['abs_max_n'] - pn) / max(1e-6, (meta['abs_max_n'] - meta['abs_min_n'])) * h))
                    if 0 <= u < w and 0 <= v < h:
                        heat[v, u] = max(heat[v, u], ev['score'])
                    if best is None or ev['score'] > best['score']:
                        best = ev
        candidates.sort(key=lambda x: x['score'], reverse=True)
        return best, candidates, heat

    def make_heatmap(self, sat_rgb, heat):
        if heat.max() > heat.min():
            norm = ((heat - heat.min()) / (heat.max() - heat.min()) * 255).astype(np.uint8)
        else:
            norm = np.zeros_like(heat, dtype=np.uint8)
        norm = cv2.GaussianBlur(norm, (0,0), sigmaX=5, sigmaY=5)
        cmap = cv2.applyColorMap(norm, cv2.COLORMAP_JET)
        base = self.ensure_bgr(sat_rgb)
        if base.shape[:2] != cmap.shape[:2]:
            base = cv2.resize(base, (cmap.shape[1], cmap.shape[0]), interpolation=cv2.INTER_AREA)
        return cv2.addWeighted(base, 0.55, cmap, 0.45, 0)

    def draw_overlay(self, sat_rgb, sat_label, local_label, points, meta, best, heatmap=None):
        base = self.ensure_bgr(sat_rgb).copy()
        if heatmap is not None:
            if heatmap.shape[:2] != base.shape[:2]:
                heatmap = cv2.resize(heatmap, (base.shape[1], base.shape[0]), interpolation=cv2.INTER_AREA)
            base = cv2.addWeighted(base, 0.70, heatmap, 0.30, 0)
        h, w = base.shape[:2]
        # Draw semantic satellite labels lightly.
        sem_color = self.colorize_labels(sat_label)
        if sem_color.shape[:2] != base.shape[:2]:
            sem_color = cv2.resize(sem_color, (w, h), interpolation=cv2.INTER_NEAREST)
        base = cv2.addWeighted(base, 0.82, sem_color, 0.18, 0)
        # Draw transformed local semantic sample points.
        local_e, local_n, labs, wgt = points
        yaw = math.radians(float(best.get('yaw_deg', 0.0)))
        c = math.cos(yaw); s = math.sin(yaw)
        re = c * local_e - s * local_n
        rn = s * local_e + c * local_n
        ge = float(best['pose_e']) + re
        gn = float(best['pose_n']) + rn
        u = ((ge - meta['abs_min_e']) / max(1e-6, (meta['abs_max_e'] - meta['abs_min_e'])) * w).astype(np.int32)
        v = ((meta['abs_max_n'] - gn) / max(1e-6, (meta['abs_max_n'] - meta['abs_min_n'])) * h).astype(np.int32)
        inside = (u >= 0) & (u < w) & (v >= 0) & (v < h)
        # Limit draw count for speed/readability.
        idx = np.where(inside)[0]
        if len(idx) > self.args.max_overlay_points:
            rng = np.random.default_rng(123)
            idx = rng.choice(idx, self.args.max_overlay_points, replace=False)
        for i in idx:
            col = SEM_COLORS.get(int(labs[i]), (0,255,0))
            cv2.circle(base, (int(u[i]), int(v[i])), 1, col, -1)
        # Best pose marker.
        pu = int(round((best['pose_e'] - meta['abs_min_e']) / max(1e-6, (meta['abs_max_e'] - meta['abs_min_e'])) * w))
        pv = int(round((meta['abs_max_n'] - best['pose_n']) / max(1e-6, (meta['abs_max_n'] - meta['abs_min_n'])) * h))
        cv2.drawMarker(base, (pu, pv), (255, 0, 255), cv2.MARKER_CROSS, 22, 2)
        txt = 'semantic score={:.3f} sem={:.2f} cov={:.2f} dt={:.1f}px yaw={:.1f} dx={:.1f} dy={:.1f}'.format(
            best.get('score',0), best.get('sem_score',0), best.get('coverage',0), best.get('mean_dt',0),
            best.get('yaw_deg',0), best.get('dx',0), best.get('dy',0))
        cv2.rectangle(base, (5, 5), (min(w-5, 850), 45), (0, 0, 0), -1)
        cv2.putText(base, txt, (12, 32), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255,255,255), 2, cv2.LINE_AA)
        return base

    def reject_result(self, req, reason, extra=None):
        r = {
            'request_id': req.get('request_id', ''),
            'accepted': False,
            'reason': reason,
            'matcher': 'semantic_map',
            'matches': 0,
            'inliers': 0,
            'inlier_ratio': 0.0,
            'confidence': 0.0,
        }
        if extra:
            r.update(extra)
        return r

    def accept_result(self, req, best, candidates, stats, paths):
        # Peak uniqueness: compare best score with next sufficiently different candidate.
        second = candidates[1] if len(candidates) > 1 else {'score': 0.0}
        peak_delta = float(best['score'] - second['score'])
        peak_ratio = float(best['score'] / max(1e-6, second['score']))
        accepted = True
        reason = 'semantic_accepted'
        if best['score'] < self.args.min_score:
            accepted = False; reason = 'semantic_score_low'
        elif best['coverage'] < self.args.min_coverage:
            accepted = False; reason = 'semantic_coverage_low'
        elif best['inside_ratio'] < self.args.min_inside_ratio:
            accepted = False; reason = 'semantic_inside_low'
        elif peak_delta < self.args.peak_delta_min and peak_ratio < self.args.peak_ratio_min:
            accepted = False; reason = 'semantic_peak_not_unique'
        inliers = int(round(best['coverage'] * best['inside_count']))
        matches = int(best['inside_count'])
        result = {
            'request_id': req.get('request_id', ''),
            'accepted': bool(accepted),
            'reason': reason,
            'matcher': 'semantic_map',
            'meas_e': float(best['pose_e']),
            'meas_n': float(best['pose_n']),
            'confidence': float(best['score']),
            'semantic_score': float(best['sem_score']),
            'coverage': float(best['coverage']),
            'mean_dt': float(best['mean_dt']),
            'boundary_score': float(best['boundary_score']),
            'inside_ratio': float(best['inside_ratio']),
            'matches': matches,
            'inliers': inliers,
            'inlier_ratio': float(best['coverage']),
            'rotation_deg': float(best['yaw_deg']),
            'scale': 1.0,
            'variance': float(max(1.0, self.args.base_variance / max(0.05, best['score']))),
            'dx': float(best['dx']),
            'dy': float(best['dy']),
            'peak_delta': peak_delta,
            'peak_ratio': peak_ratio,
        }
        result.update(stats)
        result.update(paths)
        return result

    def process_request(self, ready_path):
        req = self.read_json(ready_path)
        rid = req.get('request_id', Path(ready_path).stem.replace('ready_', ''))
        meta = self.meta_dict(req)
        out_prefix = self.output_dir / rid
        result_path = self.output_dir / ('result_%s.json' % rid)

        # Prefer semantic source images. Fall back to old mono images if missing.
        bev_sem_path = req.get('bev_sem_path') or req.get('bev_path')
        sat_rgb_path = req.get('sat_rgb_path') or req.get('sat_path')
        bev_struct_path = req.get('bev_path')
        sat_struct_path = req.get('sat_path')
        bev_sem_img = cv2.imread(bev_sem_path, cv2.IMREAD_UNCHANGED)
        sat_rgb = cv2.imread(sat_rgb_path, cv2.IMREAD_COLOR)
        bev_struct = cv2.imread(bev_struct_path, cv2.IMREAD_GRAYSCALE) if bev_struct_path else None
        sat_struct = cv2.imread(sat_struct_path, cv2.IMREAD_GRAYSCALE) if sat_struct_path else None
        if bev_sem_img is None or sat_rgb is None:
            r = self.reject_result(req, 'image_read_failed', {'bev_sem_path': bev_sem_path, 'sat_rgb_path': sat_rgb_path})
            self.write_json_atomic(result_path, r)
            return

        # Resize only for computational load; physical extents remain from meta.
        bev_sem_img, _ = self.largest_dim_resize(bev_sem_img, self.args.max_local_dim)
        if bev_struct is not None:
            bev_struct = cv2.resize(bev_struct, (bev_sem_img.shape[1], bev_sem_img.shape[0]), interpolation=cv2.INTER_AREA)
        sat_rgb, _ = self.largest_dim_resize(sat_rgb, self.args.max_sat_dim)
        if sat_struct is not None:
            sat_struct = cv2.resize(sat_struct, (sat_rgb.shape[1], sat_rgb.shape[0]), interpolation=cv2.INTER_AREA)

        local_label = self.infer_local_semantic(bev_sem_img, bev_struct)
        sat_label = self.infer_satellite_semantic(sat_rgb, sat_struct)
        points, stats = self.local_points(local_label, meta)
        if points is None:
            r = self.reject_result(req, 'local_semantic_too_sparse', stats)
            self.write_json_atomic(result_path, r)
            return

        sat_boundary = self.semantic_boundary(sat_label)
        inv = (1 - sat_boundary).astype(np.uint8) * 255
        sat_dist = cv2.distanceTransform(inv, cv2.DIST_L2, 5).astype(np.float32)
        best, candidates, heat = self.search(points, sat_label, sat_dist, meta)
        if best is None:
            r = self.reject_result(req, 'no_valid_candidate', stats)
            self.write_json_atomic(result_path, r)
            return

        # Visualizations.
        heatmap_img = self.make_heatmap(sat_rgb, heat)
        overlay = self.draw_overlay(sat_rgb, sat_label, local_label, points, meta, best, heatmap_img)
        local_sem_vis = self.colorize_labels(local_label)
        sat_sem_vis = self.colorize_labels(sat_label)
        heatmap_path = str(self.output_dir / ('semantic_heatmap_%s.png' % rid))
        overlay_path = str(self.output_dir / ('semantic_overlay_%s.png' % rid))
        local_sem_path = str(self.output_dir / ('semantic_local_%s.png' % rid))
        sat_sem_path = str(self.output_dir / ('semantic_sat_%s.png' % rid))
        debug_path = overlay_path
        if self.args.publish_debug:
            cv2.imwrite(heatmap_path, heatmap_img)
            cv2.imwrite(overlay_path, overlay)
            cv2.imwrite(local_sem_path, local_sem_vis)
            cv2.imwrite(sat_sem_path, sat_sem_vis)
        paths = {
            'debug_path': debug_path,
            'heatmap_path': heatmap_path,
            'overlay_path': overlay_path,
            'local_semantic_path': local_sem_path,
            'satellite_semantic_path': sat_sem_path,
        }
        result = self.accept_result(req, best, candidates, stats, paths)
        self.write_json_atomic(result_path, result)
        print('[INFO] request %s semantic %s score=%.3f sem=%.3f cov=%.3f dt=%.2f e=%.2f n=%.2f yaw=%.1f reason=%s' % (
            rid, 'ACCEPT' if result['accepted'] else 'REJECT', result.get('confidence',0), result.get('semantic_score',0),
            result.get('coverage',0), result.get('mean_dt',0), result.get('meas_e',0), result.get('meas_n',0),
            result.get('rotation_deg',0), result.get('reason','')))

    def move_done(self, ready_path):
        if not self.args.move_processed:
            try:
                os.remove(ready_path)
            except Exception:
                pass
            return
        try:
            dst = self.done_dir / os.path.basename(ready_path)
            shutil.move(ready_path, str(dst))
        except Exception:
            try:
                os.remove(ready_path)
            except Exception:
                pass

    def spin(self):
        while True:
            ready = sorted(glob.glob(str(self.input_dir / 'ready_*.json')))
            if not ready:
                time.sleep(self.args.poll_interval)
                continue
            for rp in ready[:self.args.max_requests_per_cycle]:
                try:
                    self.process_request(rp)
                except Exception as exc:
                    print('[ERROR] failed request %s: %s' % (rp, exc))
                    try:
                        req = self.read_json(rp)
                        result_path = self.output_dir / ('result_%s.json' % req.get('request_id', Path(rp).stem))
                        self.write_json_atomic(result_path, self.reject_result(req, 'exception', {'exception': str(exc)}))
                    except Exception:
                        pass
                self.move_done(rp)


def build_argparser():
    p = argparse.ArgumentParser(description='Semantic map matching file service.')
    p.add_argument('--queue_dir', default='/tmp/eloftr_queue')
    p.add_argument('--device', default='cpu', help='Reserved for compatibility; semantic matching uses OpenCV/NumPy.')
    p.add_argument('--poll_interval', type=float, default=0.2)
    p.add_argument('--max_requests_per_cycle', type=int, default=1)
    p.add_argument('--move_processed', action='store_true', default=True)
    p.add_argument('--publish_debug', action='store_true')

    # Search settings in meters/yaw degrees.
    p.add_argument('--search_radius_m', type=float, default=35.0)
    p.add_argument('--search_step_m', type=float, default=2.0)
    p.add_argument('--yaw_degs', default='-10,-5,0,5,10')

    # Image size controls.
    p.add_argument('--max_local_dim', type=int, default=900)
    p.add_argument('--max_sat_dim', type=int, default=1400)

    # Local semantic heuristic thresholds.
    p.add_argument('--local_open_min_v', type=int, default=145)
    p.add_argument('--local_open_max_sat', type=int, default=45)
    p.add_argument('--local_obstacle_max_v', type=int, default=170)
    p.add_argument('--local_obstacle_min_sat', type=int, default=20)
    p.add_argument('--local_red_margin', type=int, default=20)
    p.add_argument('--local_structure_gray_thresh', type=int, default=105)
    p.add_argument('--local_ground_gray_thresh', type=int, default=35)

    # Satellite semantic heuristic thresholds.
    p.add_argument('--sat_green_margin', type=int, default=8)
    p.add_argument('--sat_veg_min_sat', type=int, default=28)
    p.add_argument('--sat_road_max_sat', type=int, default=45)
    p.add_argument('--sat_road_min_v', type=int, default=45)
    p.add_argument('--sat_road_max_v', type=int, default=215)
    p.add_argument('--sat_building_min_v', type=int, default=145)
    p.add_argument('--sat_building_max_sat', type=int, default=85)
    p.add_argument('--sat_building_gray_min', type=int, default=135)
    p.add_argument('--sat_structure_gray_thresh', type=int, default=110)

    # Sampling / validity.
    p.add_argument('--min_local_valid_pixels', type=int, default=800)
    p.add_argument('--min_local_foreground_ratio', type=float, default=0.006)
    p.add_argument('--max_boundary_points', type=int, default=14000)
    p.add_argument('--max_interior_points', type=int, default=10000)
    p.add_argument('--max_overlay_points', type=int, default=25000)
    p.add_argument('--min_projected_points', type=int, default=500)

    # Scoring.
    p.add_argument('--compat_match_thresh', type=float, default=0.55)
    p.add_argument('--boundary_sigma_px', type=float, default=8.0)
    p.add_argument('--boundary_weight', type=float, default=2.0)
    p.add_argument('--semantic_weight', type=float, default=0.62)
    p.add_argument('--boundary_score_weight', type=float, default=0.28)
    p.add_argument('--coverage_weight', type=float, default=0.10)
    p.add_argument('--min_score', type=float, default=0.42)
    p.add_argument('--min_coverage', type=float, default=0.22)
    p.add_argument('--min_inside_ratio', type=float, default=0.65)
    p.add_argument('--peak_delta_min', type=float, default=0.025)
    p.add_argument('--peak_ratio_min', type=float, default=1.025)
    p.add_argument('--base_variance', type=float, default=9.0)
    return p


if __name__ == '__main__':
    args = build_argparser().parse_args()
    SemanticFileService(args).spin()
